name = "katelyatv"
compatibility_date = "2024-09-01"

[env.production]
name = "katelyatv"

[env.production.vars]
# 存储类型配置
NEXT_PUBLIC_STORAGE_TYPE = "d1"

# 站点配置
NEXT_PUBLIC_SITE_NAME = "KatelyaTV"
NEXT_PUBLIC_SITE_DESCRIPTION = "高性能影视播放平台"

# NextAuth 配置
NEXTAUTH_URL = "https://your-domain.pages.dev"

# 图片代理配置
IMAGE_PROXY_ENABLED = "true"

# 缓存配置
CACHE_TTL = "3600"

# CORS 配置
CORS_ORIGIN = "*"

# Rate Limiting 配置
RATE_LIMIT_MAX = "100"
RATE_LIMIT_WINDOW = "60000"

# 健康检查配置
HEALTH_CHECK_ENABLED = "true"
HEALTH_CHECK_INTERVAL = "30"

# 日志配置
LOG_LEVEL = "info"
LOG_FORMAT = "json"

# 生产环境标识
NODE_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "310c08b9-9820-4d49-ab75-09697c77a415"

[build]
command = "pnpm pages:build"
# wrangler v4 不再支持 build.environment 和 build.environment_variables
# 如果需要设置 Node 版本或其他环境变量，请使用 env.production.vars 或 Pages 项目设置
